services:
  bot:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}:latest # Используем образ из DockerHub
    container_name: ${PROJECT_NAME}
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_PUBLIC_URL=https://bloodofspring.com/bot${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_WEBHOOK_PORT=${TELEGRAM_BOT_WEBHOOK_PORT}
      - OWNER_TG_ID=${OWNER_TG_ID}
      - DOCKER_TARGET=${DOCKER_TARGET}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${TELEGRAM_BOT_WEBHOOK_PORT}:${TELEGRAM_BOT_WEBHOOK_PORT}"

  db:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${PUBLIC_POSTGRES_PORT}:5432"
    volumes:
      - /var/lib/postgresql/${PROJECT_NAME}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
